name: 'GitHub CI'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - name: Build and Test with Maven
      run: mvn verify
    - name: HPI file artifact
      uses: actions/upload-artifact@v4
      with:
        name: blackduck-sigma-plugin.hpi
        path: target/black-duck-sigma.hpi
